### PR TITLE
Fix Bug 1449653 - use theme variables from activity stream

### PR DESCRIPTION
**Pull request by rlr**
r? @k88hudson and/or @glogiotatidis ?

### CODE REVIEW

**Comment by rlr** [comment]
I should probably update the default colors below to use our bottom variables?


```
  .snippet .button-link {
    background: {{ button_background_color|default("#D7D7DB", true) }};
    color: {{ button_color|default("#0C0C0D", true) }};
```

**Comment by k88hudson** [comment]
Agreed, button colors would be good :+1:. You also probably want to take a look at other templates in https://github.com/mozmeao/snippets/tree/master/activity-stream, although some might not need to be converted (End of Year for example) @glogiotatidis what do you think?

**Comment by rlr** [comment]
oh derp. It is supposed to have a border. @glogiotatidis How do I test that specific snippet locally?

**Comment by glogiotatidis** [comment]
> oh derp. It is supposed to have a border. @glogiotatidis How do I test that specific snippet locally?

You can try https://github.com/mozmeao/snippets-service/tree/master/simple_template_server

**Comment by glogiotatidis** [comment]
@rlr is this ready for review or you want to test first?

**Comment by rlr** [comment]
@glogiotatidis I *think* it's good but I want to try to test it first for sanity.

**Comment by rlr** [comment]
OK @glogiotatidis, thanks. Tested out and buttons look OK now:

screen shot 2018-05-08 at 12 14 26 pm

**Comment by glogiotatidis** [comment]
Merged here with some fixes on the second stage buttons.
https://github.com/mozmeao/snippets/commit/235b00cb7709a236b0eb80998af6a0214f9b27d3

**Pull request closed without merging**
