### PR TITLE
Adding newsletter subscribe snippet for AS.

### PR DESCRIPTION
**Pull request by jpetto**
This PR adds a snippet that allows users to subscribe to a given newsletter.

There are 4 different scenes/views:

1. Initial - intro text with button that reveals scene 2
2. Subscribe form
3. Subscribe success message
4. Subscribe failure message

One potentially tricky part of this snippet is making sure the configured basket newsletter id is valid. It would be great to provide a pre-populated drop-down list in the admin view, but I don't think that's possible. Maybe we can provide a link in the admin to accepted/existing basket ids?

### CODE REVIEW

**Comment by jpetto** [comment]
@glogiotatidis Let me know what you think here, both in terms of the actual code and the basket id issue. Thanks!

**Comment by glogiotatidis** [comment]
> One potentially tricky part of this snippet is making sure the configured basket newsletter id is valid. It would be great to provide a pre-populated drop-down list in the admin view, but I don't think that's possible. Maybe we can provide a link in the admin to accepted/existing basket ids?

That is a valid point. The snippets team has been managing succefully those free text fields for quite a while so I think they will be fine.  I make the description of each variable available to them, in the admin area, so if you have a link or list with the accepted basket ids please update [this line](https://github.com/mozmeao/snippets/pull/130/files#diff-00a6d612fc881bc7ac52c6d96cf81772R18)

Those said I'd love to get more field types in the future... when I find the time.

**Comment by glogiotatidis** [comment]
This is good work and I think we're close. I do have some visual concerns:

 - It seems you're defining a larger font size than the default. We should try and stick to the defaults to have snippet uniformity to the maximum extend. This applies for other properties that you may have altered from the default.

 - The block snippet button in the second scene is different from the typical 'x' on the right side. Have you checked with Aaron this design? Do you have mock-up on which you based your implementation on?

**Comment by jpetto** [comment]
I am following the design spec provided in [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1404542#c11), which specifies 14px fonts and the alternate dismiss button on scene 2. The Sketch file was posted by Aaron Benson - is that the same Aaron you're referring to?

**Comment by jpetto** [comment]
Here's a screen cap of the bit of the Sketch file detailing this form:

screen shot 2017-12-08 at 9 30 04 am

**Comment by jpetto** [comment]
Added a link to the available newsletter ids.

**Comment by glogiotatidis** [comment]
> I am following the design spec provided in the bug, which specifies 14px fonts and the alternate dismiss button on scene 2. The Sketch file was posted by Aaron Benson - is that the same Aaron you're referring to?

Yes and in this case I'm fine with it.

**Comment by glogiotatidis** [comment]
@jpetto one last thing we need to change before we merge:

We globally changed the blocking button to only appear on hover in https://github.com/mozmeao/snippets-service/commit/ac832de08ba19577b42999aa42f46f47236213cd

which breaks stage 2 block button. Can you please update?

**Comment by jpetto** [comment]
Updated to always show scene 2 block button. Thanks @glogiotatidis!

**Comment by glogiotatidis** [comment]
Thanks @jpetto 🎄

**Pull request merged**
