### PR TITLE
Adding 2017 eoy fundraising snippet for Activity Stream.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
Hey @glogiotatidis here is the fundraising snippet with buttons based on the comps in here: https://mozilla.invisionapp.com/share/PDEPWO1SK#/screens/267006747

It's mostly a port from the 2016 fundraising snippet, so buttons should more or less work the same.

The only weird thing is the `setTimeout` this is due to some values added via the snippet service to the link after the show_snippet events in here. By using a setTimeout it delays getting the url so when we try to get it, the proper query params are there.

Thoughts?

**Comment by glogiotatidis** [comment]
Block button is larger than typical block button, is this intended?

**Comment by glogiotatidis** [comment]
> Block button is larger than typical block button, is this intended?

answer in https://github.com/mozmeao/snippets/pull/128#issuecomment-349228530

**Comment by glogiotatidis** [comment]
Thanks!

**Pull request merged**
